### ISSUE TITLE
Dynamically poplulated selection field breaks after dialog conversion from coral ui 2 to coral ui 3

### ISSUE THREAD

**Issue by vicky9971** [adobe/aem-modernize-tools#10]
After performing the dialog conversion, the datasource node gets removed due to which the dynamic selection field breaks after conversion.

**Comment by bstopp** [comment]
Do you have the original coral2 widget node that you are trying to convert?

**Comment by bstopp** [comment]
Dialog conversion is being removed in v2.0.
