### ISSUE TITLE
The set up page is down

### ISSUE THREAD

**Issue by GinnyGuo** [adobe/aem-modernize-tools#131]
The set up page is down (https://opensource.adobe.com/aem-modernize-tools/pages/plan-operate/set-up.html)

### Expected Behaviour
Instructions show on page
### Actual Behaviour
page not found 404
### Reproduce Scenario (including but not limited to)
https://opensource.adobe.com/aem-modernize-tools/pages/plan-operate/set-up.html
#### Steps to Reproduce
https://opensource.adobe.com/aem-modernize-tools/pages/plan-operate/set-up.html

#### Platform and Version
Mac os Chrome

**Comment by bstopp** [comment]
Looks like an issue with the automated generation & commit. I'll get it up again.
