### ISSUE TITLE
When clicking on show dialog after conversion, nothing shows

### ISSUE THREAD

**Issue by royteeuwen** [adobe/aem-modernize-tools#15]
When you converted the dialog, it shows a result link to the "converted dialog", which for example opens following link:

http://localhost:4502/apps/my-components/components/banners/base-banner/cq:dialog.html

View-pagesource of chrome does show a <coral-dialog> but it doesn't actually render it?

**Comment by bstopp** [comment]
Dialog conversion is being removed in v2.0

**Comment by LeeYanF** [comment]
> 

What functions are used to replace Dialog conversion？

**Comment by LeeYanF** [comment]
> Dialog conversion is being removed in v2.0

What functions are used to replace Dialog conversion？
