### ISSUE TITLE
Dynamically populated classic ui with options path is not converted

### ISSUE THREAD

**Issue by jasper-s** [adobe/aem-modernize-tools#18]
Quite often, we have dialogs like:

```
<some-node 
    xtype="selection"
    type="select"
    options="$PATH.some-selector.json"/>
```
Is there a recommended way to get this automatically converted, or should we manually create datasources for all these components?
Right now the result would be like this:
```
<some-node
        jcr:primaryType="nt:unstructured"
        sling:resourceType="granite/ui/components/coral/foundation/form/select">
    <items jcr:primaryType="nt:unstructured"/>
</some-node>
```

**Comment by bstopp** [comment]
Dialog conversion is being removed in v2.0.  I am tracking these issues for remedying via other means.
