### ISSUE TITLE
Following the documentation link leads to wrong page

### ISSUE THREAD

**Issue by ericvangeem** [adobe/aem-modernize-tools#2]
[https://www.adobe.com/go/aem_modernize_tools_en](https://www.adobe.com/go/aem_modernize_tools_en) leads to a page specifically about the Dialog Conversion Tool. I was expecting it to link to documentation that covers all features of this project, such as the Template Conversion Tool or Policy Conversion Tool.

**Comment by gknobloch** [comment]
That documentation is still WIP, and the redirect will be changed shortly to point to that extended documentation.

**Comment by Ikkyu-os** [comment]
The link is still wrong. any update ?

**Comment by bstopp** [comment]
Docs are on the way.

**Comment by bstopp** [comment]
Fixed with #9
