### ISSUE TITLE
AEM Modernizer Tool is failing to convert page/structure in Chrome if the pages are 1000+ (Issue is only on Chrome) 

### ISSUE THREAD

**Issue by chethanadobe** [adobe/aem-modernize-tools#205]
### Expected Behaviour

Convert page/structure successfully regardless of pages.

### Actual Behaviour

Conversion happening fine in Safari and Firefox

#### Logs taken while reproducing problem

Error : 

GET https://author-pXXXXXX-eXXXXXX.adobeaemcloud.com/mnt/overlay/aem-modernize/content/structure/job/create.template.rules.json?path=%2Fcontent%2Fgmenvolve%2Fna%2Fus%2Fen%2Fpartials%2Fvehicle-cash-incentives-sub-content%2Ftable-partials%2F2022-chevrolet-low-cab-forward-price-table&reprocess=false net::ERR_INSUFFICIENT_RESOURCES

**Comment by bstopp** [comment]
I'm not really sure this is an issue - it really isn't/wasn't intended for the UI to be used to convert that many pages at once. What you're probably running into is an issue of Chrome not having enough memory to render all the elements for the run on the page. Which isn't anything that I can fix.
