### ISSUE TITLE
Inconsistent Component Converter configuration and output in documentation

### ISSUE THREAD

**Issue by ConnorJamesLow** [adobe/aem-modernize-tools#214]
## Docs Issue
In the **Rewrite Map Properties** section of the **COMPONENT CONVERSION > CONFIGURING THE RULES**, the example rule does not match the example output.

Based on this `cq:rewriteMapProperties` node:
```json
{
  "jcr:primaryType": "nt:unstructured",
  "rewrite-map": {
    "jcr:primaryType": "nt:unstructured",
    "One": "First",
    "Two": "Middle",
    "Three": "Last"
  }
}
```

I'd expect the output to include `"First"`, `"Middle"`, and `"Last"`. Instead, the documentation shows the following input:

```json
{
  "rewriteMapPropertiesOne": {
    "jcr:primaryType": "nt:unstructured",
    "sling:resourceType": "aem-modernize/components/rewritten",
    "rewrite-map": "First"
  },
  "rewriteMapPropertiesTwo": {
    "jcr:primaryType": "nt:unstructured",
    "sling:resourceType": "aem-modernize/components/rewritten",
    "rewrite-map": "Second"
  },
  "rewriteMapPropertiesThree": {
    "jcr:primaryType": "nt:unstructured",
    "sling:resourceType": "aem-modernize/components/rewritten",
    "rewrite-map": "Third"
  }
}
```

`"First"` matches, but where did `"Second"` and `"Third"` come from?

URL: [opensource.adobe.com/aem-modernize-tools/pages/component/config.html](https://opensource.adobe.com/aem-modernize-tools/pages/component/config.html#:~:text=%22rewrite%2Dmap%22%3A%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20%22jcr%3AprimaryType%22%3A%20%22nt%3Aunstructured%22%2C%0A%20%20%20%20%20%20%20%20%20%20%20%20%22One%22%3A%20%22First%22%2C%0A%20%20%20%20%20%20%20%20%20%20%20%20%22Two%22%3A%20%22Middle%22%2C%0A%20%20%20%20%20%20%20%20%20%20%20%20%22Three%22%3A%20%22Last%22%0A%20%20%20%20%20%20%20%20%20%20%7D).

**Comment by bstopp** [comment]
I see the confusion. Let me try to clarify:

`rewriteMapProperties` Is a literal one-to-one swap of values.

In the example in the docs, there are three components in the content. But one rule will transform all three into new output.

![Configuration___Component_Converter___AEM_Modernization_Tools](https://github.com/adobe/aem-modernize-tools/assets/6520270/bff6950b-7370-4030-80a5-6ba71b56f981)


And then it processes the next node:

![Configuration___Component_Converter___AEM_Modernization_Tools](https://github.com/adobe/aem-modernize-tools/assets/6520270/a02fd39d-eb04-4716-93b0-515ced98ac1d)

Does this help?

**Comment by ConnorJamesLow** [comment]
Thanks, @bstopp. I actually understand how it works; I'm pointing out that if `Two` maps to `Middle` then the result should be

```
  "rewriteMapPropertiesTwo": {
    "jcr:primaryType": "nt:unstructured",
    "sling:resourceType": "aem-modernize/components/rewritten",
    "rewrite-map": "Middle"
  },
```

but the docs say the result is

```
  "rewriteMapPropertiesTwo": {
    "jcr:primaryType": "nt:unstructured",
    "sling:resourceType": "aem-modernize/components/rewritten",
    "rewrite-map": "Second"
  },
```

Note the `rewrite-map` property. The output is inconsistent in the example—I think it was a typo.

**Comment by bstopp** [comment]
Nope, you are absolutely correct. That is a typo in the documentation. Addressing it now.
