### ISSUE TITLE
Dialog Conversion Tool needs to encode colon in CRXDE link

### ISSUE THREAD

**Issue by dhardtke** [adobe/aem-modernize-tools#22]
The Dialog Conversion Tool currently shows links like this:
> http://localhost:4502/crx/de/index.jsp#/apps/myapp/core/components/myComp/cq:dialog

which doesn't work. CRXDE doesn't open the `cq:dialog` node but instead stops at `myComp`.

Instead, the tool should link to

> http://localhost:4502/crx/de/index.jsp#/apps/myapp/core/components/myComp/cq%3Adialog

I'm using AEM 6.5 SP2.

**Comment by dhardtke** [comment]
Just to clarify: it does encode the colon after conversion, but not before (on the overview page after the first page load)

**Comment by bstopp** [comment]
Dialog conversion is being removed in v2.0. I am tracking these issues for remedying via other means.
