### ISSUE TITLE
[Query] Page versioning after migration

### ISSUE THREAD

**Issue by manojBabuDev** [adobe/aem-modernize-tools#26]
Hello, 

After migrating static templates to editable templates using modernize tools. Will out-of-the-box functionality: reverting to page version or comparing version with current page works?

Please let us know.

https://docs.adobe.com/content/help/en/experience-manager-64/authoring/siteandpage/working-with-page-versions.html#reverting-to-a-page-version

**Comment by bstopp** [comment]
With v2.0 (forthcoming) before Structure or Full conversions, a new version of the page will be created.

You can use the UI to compare the before/after transformations were made on a page.
