### ISSUE TITLE
Policy importer doesn't copy child nodes with cq:copyChildren

### ISSUE THREAD

**Issue by TMelotte** [adobe/aem-modernize-tools#28]
According to the documentation, you can use cq:copyChildren in the rules to copy a tree of content from the designs folder to the policies folder. This does not work, as only the parent node is copied.

For example designs for the text core component cannot easily be converted. They are set up like this :
<text jcr:primaryType="nt:unstructured"
        sling:resourceType="xxx/text">
    <rtePlugins jcr:primaryType="nt:unstructured">
         <table jcr:primaryType="nt:unstructured"
                     features="*"/>
           ...
    </>
</some-node>

The only thing that gets copied to the policy is the text node

**Comment by bstopp** [comment]
This has been resolved in #63
