### ISSUE TITLE
Page Conversion Tool url encode issue with page/folders that are numerically named

### ISSUE THREAD

**Issue by toddhaser** [adobe/aem-modernize-tools#32]
### Expected Behaviour
When entering a path like: "/content/geometrixx/en/tour-top-10/2020/08/17" to search for specific templates, 'Show Pages' button should show me all templates that match the configs from OSGi

### Actual Behaviour
PageDataSource createQuery method has the following:
String encodedPath = RewriteUtils.encodePath(searchPath);  
which is giving back a result like: "/content/geometrixx/en/tour-top-10/_x0032_020/_x0030_8/_x0031_7" which then causes the jcr query to return no results.

### Reproduce Scenario (including but not limited to)
Create a folder structure/path with numerically named pages, as above.

#### Steps to Reproduce
Go to Page Template/Stucture Conversion Tool page and try to run a search against path with numerically based folder/page names (http://localhost:4502/libs/cq/modernize/templatestructure/content/console.html)

#### Platform and Version
6.5.6 and 6.5.9 - with jdk 11

**Comment by bstopp** [comment]
This has been resolved in v2.0 with #63
